### ISSUE TITLE
Comment on Blog Post re 404 status

### ISSUE THREAD

**Issue by aelfric** [kabir/blog-quarkus-ui-development#8]
Not sure if this is the right place to put this, but thought I'd mention it here since the blog doesn't allow comments. We are using a single JAR to deploy a Quarkus and ReactJS application. We used the technique found in the blog to handle frontend routing.

It worked well except we were having problems having Google index our site, and for the longest time we couldn't figure out why. We used Google's Search Console to app to see that the crawler was getting a lot of 404 errors, but anytime we went to one of the problematic URLs, it rendered with no problem.

I just realized today that the reason is that the filter recommended in the blog post preserves the 404 response status. I added this line and now those requests are handled correctly. Only time will tell if Google will be able to re-index the site now.

```
        response.setStatus(HttpServletResponse.SC_OK);
```

**Comment by kabir** [comment]
Hi @aelfric!

Glad to hear the blog was useful. It is some time since I wrote it and I've been working in a totally different area since that so it isn't fresh in my mind any longer. Would you be able to open a pull request with your code in the right place?

**Comment by aelfric** [comment]
It was definitely a useful blog post.  Thanks for writing it!

I submitted a pull request (hopefully correctly).  I've never submitted one before.

**Comment by kabir** [comment]
Thank you - I am in meetings a lot of next week. If it slips down my TODO list and I don't get to it, feel free to bug me :)

**Comment by rjumatov** [comment]
I have an issue related to this one. All redirects that I make are working correctly but if you open developer tools in the browser you can see that the first network response is a 404.
Is it possible to redirect without a brief error response?

**Comment by aelfric** [comment]
Did you try the line of code in my comment? It should take care of the status code as long as whatever front-end router you're pointing to can successfully handle the request.

For what it's worth, though, I have stopped using this approach on newer projects. I'm instead using nginx as a reverse proxy and put all the api calls to quarkus behind a prefix path that nginx can filter on. My front-end code is deployed as static resources outside of quarkus.

**Comment by rjumatov** [comment]
Yes I have tried it with your suggested line of code but unfortunately I still get the same behavior. I've tried quarkus platform version 2.0.0 (and up to 2.2.1.Final) but in none of them I could get a redirect without an initial 404 response.
In my case I rely on that the whole thing gets deployed as a single jar.

Interestingly the results are the same with and without `response.setStatus(200)`.
Maybe something has changed internally, preventing a postchange of the responseStatus.

Here is the filter I am using:
````java
@WebFilter(urlPatterns = "/*")
public class ReactRouteFilter extends HttpFilter {

	@Override
	public void doFilter(ServletRequest req, ServletResponse res, FilterChain chain)
			throws IOException, ServletException {
		HttpServletRequest request = (HttpServletRequest) req;
		HttpServletResponse response = (HttpServletResponse) res;
		chain.doFilter(request, response);

		if (response.getStatus() == 404) {
			try {
				response.setStatus(200);
				request.getRequestDispatcher("/").forward(request, response);
			} finally {
				response.getOutputStream().close();
			}
		}
	}
}
````

**Comment by aelfric** [comment]
Since you wrote it only happens on the first redirect, is it possible the 404 is coming from the front-end router?

**Comment by rjumatov** [comment]
I am sorry I mean the first redirect of course. Is it possible to set the status of a first redirect to 200?
In my case the consumer typically bookmarks certain routes and a 404 on every startup (even if its just in the dev tools) is something I would like to get rid of.

**Comment by rjumatov** [comment]
I've looked into the `response.setStatus()` method and by logging the response-status before and after that line I've seen that the responseStatus does not change at all. It remains 404. From the docs of `setStatus(int sc)`:

>  This method is used to set the return status code when there is no error (for example, for the SC_OK or SC_MOVED_TEMPORARILY status codes).

**Comment by rjumatov** [comment]
I've found a workaround. Since I cannot set the status of a 404 response, I cleared it and now I do not encounter any 404 redirection errors on startup. This made it work:

Replace `response.setStatus(200)` with `response.reset()`.

Since a 404 does not contain any further data, resetting does not seem to be a problem in this case.
